model: fasterrcnn_resnet50_fpn
data: data_configs/rock-paper-scissors.yaml
device: cuda
epochs: 20
workers: 4
batch: 16
lr: 0.001
imgsz: 640
name: rock-paper-scissors
vis_transformed: false
mosaic: 0.0
use_train_aug: false
cosine_annealing: false
weights: null
resume_training: false
square_training: false
world_size: 1
dist_url: env://
disable_wandb: false
sync_bn: false
amp: false
seed: 0
project_dir: null
distributed: false
